window.SHEET_DATA = {
  "spreadsheetId": "1-cD3fe5xXmmVBZ7RAXfrpfpDtXt553uJmfVzIijF1_k",
  "sourceUrl": "https://docs.google.com/spreadsheets/d/1-cD3fe5xXmmVBZ7RAXfrpfpDtXt553uJmfVzIijF1_k/edit?usp=sharing",
  "tabs": [
    "업무일지",
    "업무현황",
    "자재현황",
    "최종현황",
    "환경설정"
  ],
  "config": {
    "processes": [
      {
        "name": "토목공사",
        "subs": [
          "선형공사(부지정리·절토·성토 포함)",
          "옹벽·석축공사",
          "배관공사(상·오·우수)",
          "전기공사(인입·관로)",
          "배수로공사",
          "정화조공사",
          "토목기타공사"
        ]
      },
      {
        "name": "관리동",
        "subs": [
          "기초공사",
          "골조공사",
          "외벽공사",
          "창호공사",
          "내부마감공사",
          "건축기타공사",
          "내부인테리어"
        ]
      },
      {
        "name": "글램핑",
        "subs": [
          "글램핑기초공사",
          "글램핑골조공사",
          "외벽천막공사",
          "글램핑창호공사",
          "글램핑내부마감공사",
          "글램핑기타공사",
          "글램핑내부인테리어"
        ]
      },
      {
        "name": "부대토목(조경)",
        "subs": [
          "내부도로및 포장",
          "사이트바닥",
          "데크공사",
          "울타리공사",
          "조경,식재",
          "기타마감"
        ]
      },
      {
        "name": "기타시설",
        "subs": [
          "수영장",
          "놀이터",
          "반려견",
          "기타시설",
          "전기설비",
          "조명공사",
          "통신공사",
          "cctv",
          "방송설비",
          "간판및안내판"
        ]
      }
    ],
    "equipment": [
      "공투",
      "6w",
      "10.0",
      "펌프카",
      "레미콘",
      "크레인",
      "03w",
      "지게차",
      " 진동로라",
      "덤프카15T"
    ],
    "labor": [
      "인원35",
      "인원30",
      "인원28",
      "인원25",
      "인원20",
      "인원18",
      "현장소장",
      "지게차",
      "인원100"
    ],
    "payments": [
      "현장결제",
      "결제완료",
      "카드결제",
      "외상"
    ],
    "workAmounts": [
      1,
      0.5,
      4
    ],
    "costTypes": [
      "장비대",
      "인건비"
    ]
  },
  "workEntries": [
    {
      "id": "sheet-work-7",
      "sourceRow": 7,
      "date": "2026-03-07",
      "mainProcess": "토목공사",
      "subProcess": "토목기타공사",
      "detailProcess": "철거",
      "equipment": "공투",
      "labor": "",
      "workAmount": 1,
      "costType": "장비대",
      "cost": 700000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-8",
      "sourceRow": 8,
      "date": "2026-03-08",
      "mainProcess": "토목공사",
      "subProcess": "토목기타공사",
      "detailProcess": "철거",
      "equipment": "공투",
      "labor": "",
      "workAmount": 1,
      "costType": "장비대",
      "cost": 700000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-9",
      "sourceRow": 9,
      "date": "2026-03-08",
      "mainProcess": "토목공사",
      "subProcess": "토목기타공사",
      "detailProcess": "\"",
      "equipment": "",
      "labor": "인원18",
      "workAmount": 1,
      "costType": "인건비",
      "cost": 180000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-10",
      "sourceRow": 10,
      "date": "2026-03-09",
      "mainProcess": "토목공사",
      "subProcess": "토목기타공사",
      "detailProcess": "폐기물분류및목재반출",
      "equipment": "",
      "labor": "인원18",
      "workAmount": 1,
      "costType": "인건비",
      "cost": 180000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-11",
      "sourceRow": 11,
      "date": "2026-03-10",
      "mainProcess": "토목공사",
      "subProcess": "토목기타공사",
      "detailProcess": "\"",
      "equipment": "공투",
      "labor": "",
      "workAmount": 1,
      "costType": "장비대",
      "cost": 700000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-12",
      "sourceRow": 12,
      "date": "2026-03-10",
      "mainProcess": "토목공사",
      "subProcess": "토목기타공사",
      "detailProcess": "\"",
      "equipment": "덤프카15T",
      "labor": "",
      "workAmount": 1,
      "costType": "장비대",
      "cost": "",
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-13",
      "sourceRow": 13,
      "date": "2026-03-11",
      "mainProcess": "토목공사",
      "subProcess": "토목기타공사",
      "detailProcess": "혼합폐기물반출및분류",
      "equipment": "공투",
      "labor": "",
      "workAmount": 1,
      "costType": "장비대",
      "cost": 700000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-14",
      "sourceRow": 14,
      "date": "2026-03-11",
      "mainProcess": "토목공사",
      "subProcess": "토목기타공사",
      "detailProcess": "\"",
      "equipment": "덤프카15T",
      "labor": "",
      "workAmount": 1,
      "costType": "장비대",
      "cost": "",
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-15",
      "sourceRow": 15,
      "date": "2026-03-12",
      "mainProcess": "토목공사",
      "subProcess": "토목기타공사",
      "detailProcess": "혼합.폐콘크리트반출",
      "equipment": "공투",
      "labor": "",
      "workAmount": 1,
      "costType": "장비대",
      "cost": 700000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-16",
      "sourceRow": 16,
      "date": "2026-03-12",
      "mainProcess": "토목공사",
      "subProcess": "토목기타공사",
      "detailProcess": "\"",
      "equipment": "덤프카15T",
      "labor": "",
      "workAmount": 1,
      "costType": "장비대",
      "cost": "",
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-17",
      "sourceRow": 17,
      "date": "2026-03-12",
      "mainProcess": "토목공사",
      "subProcess": "토목기타공사",
      "detailProcess": "\"",
      "equipment": "덤프카15T",
      "labor": "",
      "workAmount": 1,
      "costType": "장비대",
      "cost": "",
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-18",
      "sourceRow": 18,
      "date": "2026-03-23",
      "mainProcess": "토목공사",
      "subProcess": "토목기타공사",
      "detailProcess": "절토량처리,하천석축쌓기",
      "equipment": "덤프카15T",
      "labor": "",
      "workAmount": 1,
      "costType": "장비대",
      "cost": "",
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-19",
      "sourceRow": 19,
      "date": "2026-03-23",
      "mainProcess": "토목공사",
      "subProcess": "토목기타공사",
      "detailProcess": "\"",
      "equipment": "공투",
      "labor": "",
      "workAmount": 1,
      "costType": "장비대",
      "cost": 700000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-20",
      "sourceRow": 20,
      "date": "2026-03-24",
      "mainProcess": "토목공사",
      "subProcess": "토목기타공사",
      "detailProcess": "하천석축쌓기,관리동터파기",
      "equipment": "공투",
      "labor": "",
      "workAmount": 1,
      "costType": "장비대",
      "cost": 700000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-21",
      "sourceRow": 21,
      "date": "2026-03-25",
      "mainProcess": "관리동",
      "subProcess": "기초공사",
      "detailProcess": "거푸집설치및 배관위치표기",
      "equipment": "공투",
      "labor": "",
      "workAmount": 1,
      "costType": "장비대",
      "cost": 700000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-22",
      "sourceRow": 22,
      "date": "2026-03-25",
      "mainProcess": "관리동",
      "subProcess": "기초공사",
      "detailProcess": "\"",
      "equipment": "",
      "labor": "인원25",
      "workAmount": 1,
      "costType": "인건비",
      "cost": 250000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-23",
      "sourceRow": 23,
      "date": "2026-03-26",
      "mainProcess": "관리동",
      "subProcess": "기초공사",
      "detailProcess": "\"(건축주변경으로3번재설치)",
      "equipment": "공투",
      "labor": "",
      "workAmount": 1,
      "costType": "장비대",
      "cost": 700000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-24",
      "sourceRow": 24,
      "date": "2026-03-26",
      "mainProcess": "관리동",
      "subProcess": "기초공사",
      "detailProcess": "\"",
      "equipment": "",
      "labor": "인원25",
      "workAmount": "",
      "costType": "인건비",
      "cost": 250000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-25",
      "sourceRow": 25,
      "date": "2026-03-27",
      "mainProcess": "관리동",
      "subProcess": "기초공사",
      "detailProcess": "배관설치및단열재깔기",
      "equipment": "공투",
      "labor": "",
      "workAmount": 1,
      "costType": "장비대",
      "cost": 700000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-26",
      "sourceRow": 26,
      "date": "2026-03-27",
      "mainProcess": "관리동",
      "subProcess": "기초공사",
      "detailProcess": "\"",
      "equipment": "",
      "labor": "인원25",
      "workAmount": "",
      "costType": "인건비",
      "cost": 250000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-27",
      "sourceRow": 27,
      "date": "2026-03-27",
      "mainProcess": "관리동",
      "subProcess": "기초공사",
      "detailProcess": "\"",
      "equipment": "",
      "labor": "인원25",
      "workAmount": "",
      "costType": "인건비",
      "cost": 250000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-28",
      "sourceRow": 28,
      "date": "2026-03-27",
      "mainProcess": "관리동",
      "subProcess": "기초공사",
      "detailProcess": "\"",
      "equipment": "",
      "labor": "인원18",
      "workAmount": "",
      "costType": "인건비",
      "cost": 180000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-29",
      "sourceRow": 29,
      "date": "2026-03-28",
      "mainProcess": "관리동",
      "subProcess": "기초공사",
      "detailProcess": "철근조립,내부칸막이각관으로위치표기",
      "equipment": "공투",
      "labor": "",
      "workAmount": 1,
      "costType": "장비대",
      "cost": 700000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-30",
      "sourceRow": 30,
      "date": "2026-03-28",
      "mainProcess": "관리동",
      "subProcess": "기초공사",
      "detailProcess": "\"",
      "equipment": "",
      "labor": "인원25",
      "workAmount": "",
      "costType": "인건비",
      "cost": 250000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-31",
      "sourceRow": 31,
      "date": "2026-03-28",
      "mainProcess": "관리동",
      "subProcess": "기초공사",
      "detailProcess": "\"",
      "equipment": "",
      "labor": "인원25",
      "workAmount": "",
      "costType": "인건비",
      "cost": 250000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-32",
      "sourceRow": 32,
      "date": "2026-03-28",
      "mainProcess": "관리동",
      "subProcess": "기초공사",
      "detailProcess": "",
      "equipment": "",
      "labor": "인원18",
      "workAmount": "",
      "costType": "인건비",
      "cost": 180000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-33",
      "sourceRow": 33,
      "date": "2026-04-01",
      "mainProcess": "관리동",
      "subProcess": "기초공사",
      "detailProcess": "콘크리트타설",
      "equipment": "펌프카",
      "labor": "",
      "workAmount": 1,
      "costType": "장비대",
      "cost": "",
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-34",
      "sourceRow": 34,
      "date": "2026-04-01",
      "mainProcess": "관리동",
      "subProcess": "기초공사",
      "detailProcess": "\"",
      "equipment": "레미콘",
      "labor": "",
      "workAmount": 4,
      "costType": "장비대",
      "cost": "",
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-35",
      "sourceRow": 35,
      "date": "2026-04-01",
      "mainProcess": "관리동",
      "subProcess": "기초공사",
      "detailProcess": "\"",
      "equipment": "",
      "labor": "인원30",
      "workAmount": "",
      "costType": "인건비",
      "cost": 300000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-36",
      "sourceRow": 36,
      "date": "2026-04-01",
      "mainProcess": "관리동",
      "subProcess": "기초공사",
      "detailProcess": "\"",
      "equipment": "",
      "labor": "인원25",
      "workAmount": "",
      "costType": "인건비",
      "cost": 250000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-37",
      "sourceRow": 37,
      "date": "2026-04-01",
      "mainProcess": "관리동",
      "subProcess": "기초공사",
      "detailProcess": "\"",
      "equipment": "",
      "labor": "인원25",
      "workAmount": "",
      "costType": "인건비",
      "cost": 250000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-38",
      "sourceRow": 38,
      "date": "2026-04-06",
      "mainProcess": "관리동",
      "subProcess": "기초공사",
      "detailProcess": "먹매김,기둥각관제작,주변정리",
      "equipment": "공투",
      "labor": "",
      "workAmount": 0.5,
      "costType": "장비대",
      "cost": 350000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-39",
      "sourceRow": 39,
      "date": "2026-04-06",
      "mainProcess": "관리동",
      "subProcess": "기초공사",
      "detailProcess": "\"",
      "equipment": "",
      "labor": "인원30",
      "workAmount": 1,
      "costType": "인건비",
      "cost": 300000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-40",
      "sourceRow": 40,
      "date": "2026-04-07",
      "mainProcess": "관리동",
      "subProcess": "골조공사",
      "detailProcess": "기둥설치,트러스제작",
      "equipment": "",
      "labor": "인원30",
      "workAmount": 1,
      "costType": "인건비",
      "cost": 300000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-41",
      "sourceRow": 41,
      "date": "2026-04-07",
      "mainProcess": "관리동",
      "subProcess": "골조공사",
      "detailProcess": "\"",
      "equipment": "",
      "labor": "인원28",
      "workAmount": 1,
      "costType": "인건비",
      "cost": 280000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-42",
      "sourceRow": 42,
      "date": "2026-04-07",
      "mainProcess": "관리동",
      "subProcess": "골조공사",
      "detailProcess": "\"",
      "equipment": "",
      "labor": "인원25",
      "workAmount": 1,
      "costType": "인건비",
      "cost": 250000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-43",
      "sourceRow": 43,
      "date": "2026-04-07",
      "mainProcess": "관리동",
      "subProcess": "골조공사",
      "detailProcess": "\"",
      "equipment": "",
      "labor": "인원25",
      "workAmount": 1,
      "costType": "인건비",
      "cost": 250000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-44",
      "sourceRow": 44,
      "date": "2026-04-07",
      "mainProcess": "관리동",
      "subProcess": "골조공사",
      "detailProcess": "\"",
      "equipment": "",
      "labor": "인원20",
      "workAmount": 1,
      "costType": "인건비",
      "cost": 200000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-45",
      "sourceRow": 45,
      "date": "2026-04-08",
      "mainProcess": "관리동",
      "subProcess": "골조공사",
      "detailProcess": "트러스제작설치",
      "equipment": "",
      "labor": "인원30",
      "workAmount": "",
      "costType": "인건비",
      "cost": 300000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-46",
      "sourceRow": 46,
      "date": "2026-04-08",
      "mainProcess": "관리동",
      "subProcess": "골조공사",
      "detailProcess": "\"",
      "equipment": "",
      "labor": "인원28",
      "workAmount": 1,
      "costType": "인건비",
      "cost": 280000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-47",
      "sourceRow": 47,
      "date": "2026-04-08",
      "mainProcess": "관리동",
      "subProcess": "골조공사",
      "detailProcess": "\"",
      "equipment": "",
      "labor": "인원25",
      "workAmount": 1,
      "costType": "인건비",
      "cost": 250000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-48",
      "sourceRow": 48,
      "date": "2026-04-08",
      "mainProcess": "관리동",
      "subProcess": "골조공사",
      "detailProcess": "\"",
      "equipment": "",
      "labor": "인원25",
      "workAmount": 1,
      "costType": "인건비",
      "cost": 250000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-49",
      "sourceRow": 49,
      "date": "2026-04-08",
      "mainProcess": "관리동",
      "subProcess": "골조공사",
      "detailProcess": "\"",
      "equipment": "",
      "labor": "인원20",
      "workAmount": 1,
      "costType": "인건비",
      "cost": 200000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-50",
      "sourceRow": 50,
      "date": "2026-04-08",
      "mainProcess": "관리동",
      "subProcess": "골조공사",
      "detailProcess": "\"",
      "equipment": "크레인",
      "labor": "",
      "workAmount": 0.5,
      "costType": "장비대",
      "cost": "",
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-51",
      "sourceRow": 51,
      "date": "2026-04-28",
      "mainProcess": "관리동",
      "subProcess": "골조공사",
      "detailProcess": "판넬입고",
      "equipment": "공투",
      "labor": "",
      "workAmount": 1,
      "costType": "장비대",
      "cost": 700000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-52",
      "sourceRow": 52,
      "date": "2026-04-29",
      "mainProcess": "관리동",
      "subProcess": "외벽공사",
      "detailProcess": "",
      "equipment": "",
      "labor": "인원30",
      "workAmount": 1,
      "costType": "인건비",
      "cost": 300000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-53",
      "sourceRow": 53,
      "date": "2026-04-29",
      "mainProcess": "관리동",
      "subProcess": "외벽공사",
      "detailProcess": "",
      "equipment": "",
      "labor": "인원28",
      "workAmount": 1,
      "costType": "인건비",
      "cost": 280000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-54",
      "sourceRow": 54,
      "date": "2026-04-29",
      "mainProcess": "관리동",
      "subProcess": "외벽공사",
      "detailProcess": "",
      "equipment": "",
      "labor": "인원25",
      "workAmount": 1,
      "costType": "인건비",
      "cost": 250000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-55",
      "sourceRow": 55,
      "date": "2026-04-29",
      "mainProcess": "관리동",
      "subProcess": "외벽공사",
      "detailProcess": "",
      "equipment": "",
      "labor": "인원25",
      "workAmount": 1,
      "costType": "인건비",
      "cost": 250000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-56",
      "sourceRow": 56,
      "date": "2026-04-29",
      "mainProcess": "관리동",
      "subProcess": "외벽공사",
      "detailProcess": "",
      "equipment": "",
      "labor": "인원20",
      "workAmount": 1,
      "costType": "인건비",
      "cost": 200000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-57",
      "sourceRow": 57,
      "date": "2026-04-30",
      "mainProcess": "관리동",
      "subProcess": "외벽공사",
      "detailProcess": "",
      "equipment": "크레인",
      "labor": "",
      "workAmount": 0.5,
      "costType": "장비대",
      "cost": "",
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-58",
      "sourceRow": 58,
      "date": "2026-04-30",
      "mainProcess": "관리동",
      "subProcess": "외벽공사",
      "detailProcess": "",
      "equipment": "",
      "labor": "인원30",
      "workAmount": 1,
      "costType": "인건비",
      "cost": 300000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-59",
      "sourceRow": 59,
      "date": "2026-04-30",
      "mainProcess": "관리동",
      "subProcess": "외벽공사",
      "detailProcess": "",
      "equipment": "",
      "labor": "인원28",
      "workAmount": 1,
      "costType": "인건비",
      "cost": 280000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-60",
      "sourceRow": 60,
      "date": "2026-04-30",
      "mainProcess": "관리동",
      "subProcess": "외벽공사",
      "detailProcess": "",
      "equipment": "",
      "labor": "인원28",
      "workAmount": 1,
      "costType": "인건비",
      "cost": 280000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-61",
      "sourceRow": 61,
      "date": "2026-04-30",
      "mainProcess": "관리동",
      "subProcess": "외벽공사",
      "detailProcess": "",
      "equipment": "",
      "labor": "인원25",
      "workAmount": 1,
      "costType": "인건비",
      "cost": 250000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    },
    {
      "id": "sheet-work-62",
      "sourceRow": 62,
      "date": "2026-04-30",
      "mainProcess": "관리동",
      "subProcess": "외벽공사",
      "detailProcess": "",
      "equipment": "",
      "labor": "인원20",
      "workAmount": 1,
      "costType": "인건비",
      "cost": 200000,
      "paymentStatus": "",
      "memo": "",
      "status": "synced"
    }
  ],
  "materialOrders": [
    {
      "id": "sheet-material-7",
      "sourceRow": 7,
      "date": "2026-03-06",
      "process": "토목공사",
      "product": "현장 필요물품(테이블,로프 등)",
      "vendor": "네이버페이",
      "area": "",
      "orderAmount": 485350,
      "lowPrice": 0,
      "highPrice": 0,
      "memo": "",
      "creditAmount": ""
    },
    {
      "id": "sheet-material-8",
      "sourceRow": 8,
      "date": "2026-03-10",
      "process": "토목공사",
      "product": "4SQ 2C 100m (전선)",
      "vendor": "네이버페이",
      "area": "",
      "orderAmount": 233640,
      "lowPrice": 0,
      "highPrice": 0,
      "memo": "",
      "creditAmount": ""
    },
    {
      "id": "sheet-material-9",
      "sourceRow": 9,
      "date": "2026-03-11",
      "process": "토목공사",
      "product": "폐기물(폐콘크리트,돌) 처리",
      "vendor": "선경산업환경",
      "area": "",
      "orderAmount": 5170000,
      "lowPrice": 0,
      "highPrice": 0,
      "memo": "",
      "creditAmount": ""
    },
    {
      "id": "sheet-material-10",
      "sourceRow": 10,
      "date": "2026-03-16",
      "process": "토목공사",
      "product": "폐기물(합성폐기물) 처리",
      "vendor": "중원산업",
      "area": "",
      "orderAmount": 5280000,
      "lowPrice": 0,
      "highPrice": 0,
      "memo": "",
      "creditAmount": ""
    },
    {
      "id": "sheet-material-11",
      "sourceRow": 11,
      "date": "2026-03-19",
      "process": "토목공사",
      "product": "철근 13mm",
      "vendor": "태양철강",
      "area": "",
      "orderAmount": 1793000,
      "lowPrice": 0,
      "highPrice": 1870800,
      "memo": "",
      "creditAmount": ""
    },
    {
      "id": "sheet-material-12",
      "sourceRow": 12,
      "date": "2026-03-19",
      "process": "토목공사",
      "product": "칼라각관",
      "vendor": "태양철강",
      "area": "",
      "orderAmount": 6355800,
      "lowPrice": 0,
      "highPrice": 6554200,
      "memo": "",
      "creditAmount": ""
    },
    {
      "id": "sheet-material-13",
      "sourceRow": 13,
      "date": "2026-03-19",
      "process": "토목공사",
      "product": "단열재",
      "vendor": "벽산인슈테크",
      "area": "",
      "orderAmount": 1993200,
      "lowPrice": 0,
      "highPrice": 3548160,
      "memo": "",
      "creditAmount": ""
    },
    {
      "id": "sheet-material-14",
      "sourceRow": 14,
      "date": "",
      "process": "토목공사",
      "product": "자재비용",
      "vendor": "대한종합건재",
      "area": "",
      "orderAmount": 2134220,
      "lowPrice": 0,
      "highPrice": 2384500,
      "memo": "",
      "creditAmount": ""
    },
    {
      "id": "sheet-material-15",
      "sourceRow": 15,
      "date": "",
      "process": "토목공사",
      "product": "판넬",
      "vendor": "에이치피코리아",
      "area": "",
      "orderAmount": 24343594,
      "lowPrice": 0,
      "highPrice": 0,
      "memo": "",
      "creditAmount": 9343594
    },
    {
      "id": "sheet-material-16",
      "sourceRow": 16,
      "date": "",
      "process": "토목공사",
      "product": "자재비용",
      "vendor": "대한종합건재",
      "area": "",
      "orderAmount": 284980,
      "lowPrice": 0,
      "highPrice": 0,
      "memo": "",
      "creditAmount": 284980
    }
  ],
  "dashboard": {
    "constructionStartDate": "2026-03-07",
    "workDays": 60,
    "elapsedDays": 54,
    "materialComparisonProfit": 0,
    "realConstructionCost": 55665210,
    "totalConstructionCost": 65293784,
    "totalRatio": 1.172972922,
    "categoryCosts": [
      {
        "name": "???",
        "total": 8470000,
        "ratio": 0.1297213836,
        "credit": 0
      },
      {
        "name": "???",
        "total": 48073784,
        "ratio": 0.7362689226,
        "credit": 9628574
      },
      {
        "name": "???",
        "total": 8750000,
        "ratio": 0.1340096938,
        "credit": 9628574
      },
      {
        "name": "??",
        "total": "",
        "ratio": 0,
        "credit": ""
      },
      {
        "name": "??",
        "total": 14500000,
        "ratio": 0.2220732068,
        "credit": ""
      },
      {
        "name": "??",
        "total": 9628574,
        "ratio": 0.1474654004,
        "credit": ""
      }
    ],
    "processCosts": [
      {
        "process": "토목공사",
        "total": 53333784,
        "material": 48073784,
        "materialRatio": 0.9013758334,
        "labor": 360000,
        "laborRatio": 0.006749942963,
        "equipment": 4900000,
        "equipmentRatio": 0.09187422366,
        "overallRatio": 0.8168278928
      },
      {
        "process": "관리동",
        "total": 11960000,
        "material": 0,
        "materialRatio": 0,
        "labor": 8110000,
        "laborRatio": 0.6780936455,
        "equipment": 3850000,
        "equipmentRatio": 0.3219063545,
        "overallRatio": 0.1831721072
      },
      {
        "process": "글램핑",
        "total": 0,
        "material": 0,
        "materialRatio": "",
        "labor": 0,
        "laborRatio": "",
        "equipment": 0,
        "equipmentRatio": "",
        "overallRatio": 0
      },
      {
        "process": "부대토목(조경)",
        "total": 0,
        "material": 0,
        "materialRatio": "",
        "labor": 0,
        "laborRatio": "",
        "equipment": 0,
        "equipmentRatio": "",
        "overallRatio": 0
      },
      {
        "process": "기타시설",
        "total": 0,
        "material": 0,
        "materialRatio": "",
        "labor": 0,
        "laborRatio": "",
        "equipment": 0,
        "equipmentRatio": "",
        "overallRatio": 0
      }
    ]
  }
};
